device: 'cuda'
amp: True
pin_memory: True
non_blocking: True
prefetch: False

checkpoint_load:
checkpoint_save:
log:
dataset_path: './data'
dataset: 'gtsrb'

epochs: 100
batch_size: 256
num_workers: 4
lr: 0.01
lr_scheduler: CosineAnnealingLR
model: 'preactresnet18'

client_optimizer: 'sgd'
sgd_momentum: 0.9 
wd: 5.0e-4
frequency_save: 0

random_seed: 0

ensemble_detect_min_thr: 1
pois_model_arch: 64P,10-10P,16-16P
pois_train_perc: 0.8
pois_max_epochs: 20
max_instances_for_variance: 20
min_instances_for_variance: 5
pois_class_detect_alpha_thr: 1.0e-2
pattern_min_asr: 0.33
detector_train_perc: 1.0
detector_max_epochs: 20
retrain_pois_method: suppress

no_retrain: True
