attack_label_trans: all2one
attack_target: 0
pratio: 0.1
attack: maskblended
attack_trigger_img_path: ./resource/blended/hello_kitty.jpeg
attack_trigger_mask_path: ./resource/blended/hello_kitty_mask.png
attack_train_blended_alpha: 0.2
attack_test_blended_alpha: 0.2